# Please do not edit this file!
# It lists all the application Settings, and their default values.
# If you want to override any of the listed options,
# you can do it in local_settings.py
debug = False
logging = 'error'
address = '0.0.0.0'
port = 8000

try:
    from local_settings import *
except ImportError:
    pass
